final_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
    path('hh/', include('hh.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hh/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'hh'
urlpatterns = [
    path('hh_auth/', views.headhunter_login, name='hh_auth'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('callback/', views.headhunter_callback, name='headhunter_callback'),
    # path('resume_upload/', views.resume_upload_form, name='resume_upload_form'),
    # path('resume_upload_success/<int:resume_id>/', views.resume_upload_success, name='resume_upload_success'),
    path('', views.index, name='index'),
    path('resume/', views.get_all_resumes, name='get_all_resumes'),
    path('resume/json/', views.get_all_resumes_json, name='get_all_resumes_json'),
    path('resume/<str:resume_id>/', views.get_resume, name='get_resume'),
    path('resume/<str:resume_id>/json/', views.get_resume_json, name='get_resume_json'),
    path('resume/<str:resume_id>/find_errors/', views.get_resume_find_errors, name='get_resume_find_errors'),
    path('resume/<str:resume_id>/best/', views.get_resume_best, name='get_resume_best'),
    path('resume/<str:resume_id>/vacancy/<int:vacancy_id>/check/', views.get_resume_vacancy_check, name='get_resume_vacancy_check'),
    path('resume/<str:resume_id>/vacancy/', views.get_resume_vacancy, name='get_resume_vacancy'),
    path('resume/<str:resume_id>/vacancy/json/', views.get_resume_vacancy_json, name='get_resume_vacancy_json'),
    path('resume/<str:resume_id>/vacancy/<int:vacancy_id>/', views.get_resume_vacancy_detail, name='get_resume_vacancy_detail'),
    path('resume/<str:resume_id>/vacancy/<int:vacancy_id>/json/', views.get_resume_vacancy_detail_json, name='get_resume_vacancy_detail_json'),
    path('resume/error', views.get_resume_error_page, name='get_resume_error_page'),
]
# hh/resume/get_resume_error_page.html
# /hh/search? - поиск вакансий
# /hh/vacancy/ - список сохраненных вакансий 
# /hh/vacancy/id - вакансия детально
# /hh/vacancy/id/resume_id/ - анализ вакансии и резюме с помощью чата jpt
# /hh/resumes/ - список моих резюме
# /hh/resume/id - резюме детально
# /hh/bot/send - отправка резюме телеграмм ботом

hh/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings

# Create your models here.

# hh_auth_token
# token, refresh_token
class HeadHunterToken(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    access_token = models.TextField()
    refresh_token = models.TextField()
    expires_at = models.DateTimeField(null=True, blank=True)  # время, когда access_token станет недействителен
    updated_at = models.DateTimeField(null=True, auto_now=True)

    def is_expired(self):
        return self.expires_at and self.expires_at <= timezone.now()

# hh_my_resumes
# resume_id, active/status
class Resume(models.Model):
    status = models.TextField()
    text = models.TextField()
    file_url = models.TextField()
    title = models.CharField(max_length=255)
    file = models.FileField(upload_to='resumes/', null=True, blank=True)
    hh_resume_id = models.IntegerField(null=True)

    def __str__(self):
        return f"Resume {self.id}"

# hh_vacancy
# vacancy_id, is_favorite, был_отклик

class Vacancy(models.Model):
    vacancy_id = models.IntegerField(unique=True, db_index=True)
    status = models.TextField()

# сопроводительные тексты
class CoverLetter(models.Model):
    resume_id = models.ForeignKey(Resume, on_delete=models.CASCADE)
    text = models.TextField()
    
# vacancy_search

hh/forms.py
from django import forms
import os

# class ResumeForm(forms.ModelForm):
#     class Meta:
#         model = Resume
#         fields = ['file']
#         widgets = {
#             'Резюме (.pdf)': forms.FileInput(attrs={'class': 'form-control'}),
#         }

#         # Валидация файла .docs
#         def clean_file(self):
#             file = self.cleaned_data.get('file')
#             if file:
#                 ext = os.path.splitext(file.name)[1].lower()
#                 if ext != '.pdf':
#                     raise forms.ValidationError("Загружать можно только файлы формата .docx")
#             return file



class ErrorsInResumeForm(forms.Form):
    resume_id = forms.CharField(
        widget=forms.HiddenInput(),
    )

class DoBestResumeForm(forms.Form):
    resume_id = forms.CharField(
        widget=forms.HiddenInput(),
    )

class SearchVacancyInResumePage(forms.Form):
    resume_text = forms.CharField(
        widget=forms.HiddenInput(),
    )

hh/views.py
from django.shortcuts import render,  get_object_or_404
import requests
from urllib.parse import urlencode
from django.conf import settings
from django.shortcuts import redirect
from django.urls import reverse
from django.http import HttpResponse, JsonResponse

from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login
from .forms import ErrorsInResumeForm, DoBestResumeForm, SearchVacancyInResumePage
from io import StringIO
from pdfminer.high_level import extract_text
from .models import Resume
import re
from django.utils import timezone
import datetime
from .models import HeadHunterToken
from openai import OpenAI
from django.contrib.auth.decorators import login_required



import asyncio


# Create your views here.
client = OpenAI(api_key=settings.OPEN_AI_KEY)

# авторизация на индексной странице, после авторизации проверяем авторизацию в hh
def index(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('hh:hh_auth') 
    else:
        form = AuthenticationForm(request)
    return render(request, 'hh/index.html', {'form': form})

# форма для загрузки резюме
# def resume_upload_form(request):
#     # if request.method == 'POST':
#     #     form = ResumeForm(request.POST, request.FILES)
#     #     if form.is_valid():
#     #         resume = form.save()
#     #         file_path = resume.file.path   
#     #         text = parse_resume(file_path) 
#     #         title = get_resume_title(text)  
#     #         resume.title = title
#     #         resume.text = text
#     #         resume.save()
#     #         return redirect('hh:resume_upload_success', resume_id=resume.id)
#     # else:
#     #     form = ResumeForm()
#     # return render(request, 'hh/resume_upload.html', {'form': form})
#     pass

# # страница подтверждения загрузки резюме
# def resume_upload_success(request, resume_id: int):
#     resume = get_object_or_404(Resume, id=resume_id)
#     return render(request, 'hh/resume_upload_success.html', {'resume': resume})

# # pdf парсинг
# def parse_resume(file_path: str):
#     return extract_text(file_path)

# Название резюме
# def get_resume_title(text: str):
#     pattern = r"Желаемая должность и зарплата[:\s]*(.*?)[\s]*Специализации:"
#     match = re.search(pattern, text, re.DOTALL)

#     if match:
#         result = match.group(1).strip()
#         # Удаляем все переносы строк и заменяем последовательности пробелов на один пробел
#         result_clean = re.sub(r'\s+', ' ', result)
#         return result_clean
#     else:
#         return ''
    
#     # doc = Document((file_path)
#     # full_text = "\n".join([paragraph.text for paragraph in doc.paragraphs])
#     # return full_text



# Авторизация в Хх
@login_required(login_url='/hh/')
def headhunter_login(request):
   
    auth_url = "https://hh.ru/oauth/authorize"  
    params = {
        'response_type': 'code',
        'client_id': settings.HEADHUNTER_CLIENT_ID,
        'redirect_uri': settings.HEADHUNTER_REDIRECT_URI,
    }
    url = f"{auth_url}?{urlencode(params)}"
    return redirect(url)

# код авторизации и токен
def headhunter_callback(request):
    code = request.GET.get('code')
    if not code:
        return HttpResponse("Ошибка: код авторизации не получен", status=400)

    token_url = "https://hh.ru/oauth/token"
    data = {
        'grant_type': 'authorization_code',
        'code': code,
        'redirect_uri': settings.HEADHUNTER_REDIRECT_URI,
        'client_id': settings.HEADHUNTER_CLIENT_ID,
        'client_secret': settings.HEADHUNTER_CLIENT_SECRET,
    }

    response = requests.post(token_url, data=data)
    if response.status_code != 200:
        result = f'Ошибка при обмене кода на токен: {response.text} <br> <a href="/hh/hh_auth">Получить код авторизации заново</a>'
        return HttpResponse(result, status=response.status_code)

    token_data = response.json()
    access_token = token_data.get('access_token')
    refresh_token = token_data.get('refresh_token')
    expires_in = token_data.get('expires_in', 3600)  # число секунд до истечения токена

    expires_at = timezone.now() + datetime.timedelta(seconds=expires_in)

    # Предполагаем, что пользователь уже аутентифицирован
    token_obj, created = HeadHunterToken.objects.get_or_create(user=request.user)
    token_obj.access_token = access_token
    token_obj.refresh_token = refresh_token
    token_obj.expires_at = expires_at
    token_obj.save()

    return redirect('hh:get_all_resumes')
    # return HttpResponse("Авторизация через HeadHunter прошла успешно!")

# Обновление токена
def refresh_hh_token(token_obj):
    # Если токен не истек, возвращаем текущий
    if not token_obj.is_expired():
        return token_obj.access_token

    token_url = "https://hh.ru/oauth/token"
    data = {
        'grant_type': 'refresh_token',
        'refresh_token': token_obj.refresh_token,
        'client_id': settings.HEADHUNTER_CLIENT_ID,
        'client_secret': settings.HEADHUNTER_CLIENT_SECRET,
    }
    response = requests.post(token_url, data=data)
    if response.status_code != 200:
        raise Exception("Ошибка обновления токена")

    token_data = response.json()
    token_obj.access_token = token_data.get('access_token')
    token_obj.refresh_token = token_data.get('refresh_token')  # возможно, придёт новый refresh_token
    expires_in = token_data.get('expires_in', 3600)
    token_obj.expires_at = timezone.now() + datetime.timedelta(seconds=expires_in)
    token_obj.save()

    return token_obj.access_token

# Запрос в хх
def get_hh_data(request, method: str, params: dict = None):
    # Предполагаем, что токен уже сохранён для текущего пользователя
    token_obj = HeadHunterToken.objects.get(user=request.user)
    access_token = refresh_hh_token(token_obj)
    
    headers = {'Authorization': f'Bearer {access_token}'}
    # params = {'host': 'hh.kz'}  # Передаем параметр host
    api_url = f"https://api.hh.ru/{method}"
    response = requests.get(api_url, headers=headers, params=params)
    
    # Обработка ответа API
    if response.status_code == 200:
        return response.json()
    else:
        return {"error": "Ошибка запроса к API, нет результата", "status": response.status_code}


# Список резюме с hh
@login_required(login_url='/hh/')
def get_all_resumes(request):
    resumes = get_hh_data(request, 'resumes/mine')
    resumes_short_list = []
    for resume in resumes.get('items', []):
        resumes_short_list.append({
            'id': resume.get('id'),
            'title': resume.get('title'),
            'status': resume.get('status', {}).get('id'),
            'status_name': resume.get('status', {}).get('name'),
            'status_type': resume.get('access', {}).get('type', {}).get('id'),
            'status_type_name': resume.get('access', {}).get('type', {}).get('name')
        })
    
    # return JsonResponse(resumes_short_list, safe=False, json_dumps_params={'ensure_ascii': False}) 
    return render(request, 'hh/resume/resume.html', {'resumes': resumes_short_list})

# Список резюме с hh в json
@login_required(login_url='/hh/')
def get_all_resumes_json(request):
    resumes = get_hh_data(request, 'resumes/mine')
    resumes_short_list = []
    for resume in resumes.get('items', []):
        resumes_short_list.append({
            'id': resume.get('id'),
            'title': resume.get('title'),
            'status': resume.get('status', {}).get('id'),
            'status_name': resume.get('status', {}).get('name'),
            'status_type': resume.get('access', {}).get('type', {}).get('id'),
            'status_type_name': resume.get('access', {}).get('type', {}).get('name')
        })
    
    return JsonResponse(resumes_short_list, safe=False, json_dumps_params={'ensure_ascii': False}) 

# # резюме детально
@login_required(login_url='/hh/')
def get_resume(request, resume_id: str):
    resume = get_hh_data(request, f'/resumes/{resume_id}')
    # return JsonResponse(resume, safe=False, json_dumps_params={'ensure_ascii': False}) 
    if "error" not in resume:
        context = {
            'resume': resume,
        }
        return render(request, 'hh/resume/get_resume.html', context)
    else:
        # return JsonResponse(resume, safe=False, json_dumps_params={'ensure_ascii': False}) 
        context = {
            'error': resume["error"],
        }
        return render(request, 'hh/resume/get_resume_error_page.html', context)

# ошибка
@login_required(login_url='/hh/')
def get_resume_error_page(request, error: str):
    return render(request, 'hh/resume/get_resume_error_page.html', {'error': error})

# # резюме детально json
@login_required(login_url='/hh/')
def get_resume_json(request, resume_id: str):
    resume = get_hh_data(request, f'/resumes/{resume_id}')
    return JsonResponse(resume, safe=False, json_dumps_params={'ensure_ascii': False}) 

# Подготовка резюме для openai
def prepare_resume_for_openai(request, resume_data, form_type: str = None):
    
    if not resume_data:
        return "Нет данных резюме"

    total_text = ''

    # Название резюме
    title = resume_data.get("title", "")
    total_text += title + "\n"

    # Пример обработки: собираем текст из поля "skills"
    skills = resume_data.get("skills", "")
    total_text += "Цель: " + skills + "\n"

    # Обработка опыта работы (предполагаем, что это список словарей)
    experience_text = "Стаж работы: \n"
    for exp in resume_data.get("experience", []):
        experience_text += f"Компания: {exp.get('company', '')}\n"
        experience_text += f"Должность: {exp.get('position', '')}\n"
        experience_text += f"Описание: {exp.get('description', '')}\n"
    total_text += experience_text

    # Обработка образования (пример для основного образования)
    education_text = "Образование: \n"

hh/templates/hh/resume/get_resume.html
<!-- templates/resume_page.html -->
{% extends "resume_detail_tabs.html" %}

{% block resume_tabs_content %}
    <div class="mb-5">
        <b>Видимость резюме</b> <br>
        Статус: {{ resume.status.name }} <br>
        Видимость: {{ resume.access.type.name }} <br>
    </div>

    <div class="mb-5">
        <h5>Цель</h5>
        {{resume.skills}}
    </div>
    <div class="mb-5">
        <h5>График работы</h5>
        Занятость: {% for employment in resume.employments%} {{employment.name}}; {% endfor %} <br>
        График работы: {% for schedul in resume.schedules%} {{schedul.name}}; {% endfor %} <br>
    </div>

    <div class="mb-5">
        <h5>Навыки</h5>
        <p> 
            {% for skill in resume.skill_set %}
                {{skill}}; 
            {% endfor %}
        </p>
        <h5>Языки</h5>
        <p> 
            {% for lang in resume.language %}
                {{lang.name}} - {{lang.level.name}}; <br>
            {% endfor %}
        </p>
    </div>

    <div class="mb-5">
        <h5>Рабочий стаж</h5>
        {% for experience in resume.experience %}
            <div class="border-bottom border-secondary border-1 mb-4"> 
                <span class="text-secondary">
                    {{experience.start}} - {%if experience.end%} {{experience.end}} {%else%} по настоящее время {% endif %}
                </span>
                <p><b>{{experience.company}}</b> {{experience.position}}</p>
                <p>{{experience.description}}</p>
            </div>     
        {% endfor %}
    </div>

    <div class="mb-5">
        <h5>Образование ({{resume.education.level.name}})</h5>
        {% for education in resume.education.primary %}
            <p> 
                {{education.name}}<br>
                {{education.result}}<br>
                Год выпуска: {{education.year}}<br>
            </p>     
        {% endfor %}
    </div>

    {% if resume.education.additional %}
        <div class="mb-5">
            <h5>Доп.Образование</h5>
            {% for education in resume.education.additional %}
            <p>
            <span class="text-secondary">{{education.year}}</span><br>
                {{education.organization}}<br>
                {{education.name}}
            </p>
            {% endfor %}
        </div>
        <div class="mb-5">
            <h5>Аттестаты</h5>
            {% for education in resume.education.attestation %}
            <p>
                <span class="text-secondary">{{education.year}}</span><br>
                {{education.organization}}<br>
                {{education.name}}
            </p>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

hh/templates/hh/resume/get_resume_error_page.html
{% extends "base.html" %}

{% block title %}ОШИБКА{% endblock %}

{% block content %}
    <h2>Ошибка!</h2>
    <br>
    <b>{{error}}</b>
    
    <p><a href="{% url 'hh:get_all_resumes' %}">к списку резюме</a></p>
{% endblock %}

hh/templates/hh/resume/get_resume_with_ai_best.html
{% extends "resume_detail_tabs_cols.html" %}

{% block resume_tabs_cols_content %}

    <h5>Рекомендации:</h5>
    {% for message in ai_text %}
        {% for item in message.content %}
            <div>{{ item.text|linebreaks }}</div>
        {% endfor %}
    {% endfor %}
{% endblock %}

hh/templates/hh/resume/get_resume_with_ai_errors.html
{% extends "resume_detail_tabs_cols.html" %}

{% block resume_tabs_cols_content %}

    <h5>Рекомендации:</h5>
    {% for message in ai_text %}
        {% for item in message.content %}
            <div>{{ item.text|linebreaks }}</div>
        {% endfor %}
    {% endfor %}
{% endblock %}

hh/templates/hh/resume/get_resume_with_vacancy_detail.html
{% extends "resume_detail_tabs_cols.html" %}

{% block resume_tabs_cols_content %}

    <div style="border-bottom: 1px solid #bbb;  padding: 10px 0">
        <h4>{{vacancy.name}}</h4>
        <small><a href="{{vacancy.alternate_url}}">Смотреть на hh.kz</a></small><br>
        <small>Дата публикации: {{ vacancy.published_date}}</small><br>
        <span> 
            <b>
                {% if vacancy.salary_range.from != '' and vacancy.salary_range.to != '' %}
                {{ vacancy.salary_range.from }} - {{ vacancy.salary_range.to }}
                {% endif %}

                {% if vacancy.salary_range.from == '' and vacancy.salary_range.to != '' %}
                до {{ vacancy.salary_range.to }}
                {% endif %}

                {% if vacancy.salary_range.from != '' and vacancy.salary_range.to == '' %}
                от {{ vacancy.salary_range.from }}
                {% endif %}

                {% if vacancy.salary_range.currency != '' %} 
                    {{vacancy.salary_range.currency}}
                {% endif %}
            </b>
        </span>

        {% if vacancy.salary_range.mode.name != '' %}
           <span>
                {{ vacancy.salary_range.mode.name }}
           </span> 
        {% endif %}

        {% if vacancy.salary_range.gross != '' %}
           <span>
                {% if vacancy.salary_range.gross == true %}
                    до вычета налогов
                {% else %}
                    на руки
                {% endif %}
           </span> 
        {% endif %}

        {% if vacancy.experience != '' %}
           <p>
                Опыт работы: {{vacancy.experience.name}}
           </p> 
        {% endif %}

        {% if vacancy.schedule.name != '' %}
           <p>
                {{vacancy.schedule.name}}
           </p> 
        {% endif %}

        {% if vacancy.work_format%}
           <p>
            {% for format in vacancy.work_format%}
                {{format.name}} <br>
            {% endfor %}
           </p> 
        {% endif %}

        {% if vacancy.work_schedule_by_days%}
           <p>
                График: {% for schedule in vacancy.work_schedule_by_days %} {{schedule.name}} {% endfor %}
           </p> 
        {% endif %}

        {% if vacancy.working_hours %}
           <p>
            {% for hours in vacancy.working_hours %} {{hours.name}} {% endfor %}
           </p> 
        {% endif %}
        
        <div>
            <h4>Описание вакансии</h4>
            {{ vacancy.description|safe }}
        </div>
        <div>
            <h4>Ключевые навыки</h4>
            {% if vacancy.key_skills %}
                <p>
                    {% for skill in vacancy.key_skills %} {{skill.name}} {% endfor %}
                </p> 
            {% endif %}
            {% if vacancy.languages %}
                <p>
                    {% for skill in vacancy.languages %} {{skill.name}}: {{skill.level.name}}<br> {% endfor %}
                </p> 
            {% endif %}
        </div>

    </div>
    <p><a href="{% url 'hh:get_resume_vacancy' resume.id %}">Назад к списку вакансий</a></p>
{% endblock %}

hh/templates/hh/resume/get_resume_with_vacancy_detail_check.html
{% extends "resume_detail_tabs_cols.html" %}

{% block resume_tabs_check_tab_content %}
    {% if vacancy.id %}
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="tab4-tab" data-bs-toggle="tab" data-bs-target="#tab4" type="button" role="tab" aria-controls="tab4" aria-selected="false">
                Резюме подходит?
            </button>
        </li>
    {% endif %}
{% endblock %}

{% block resume_tabs_check_block_content %}
    {% if vacancy.id %}
        <div class="tab-pane fade p-3" id="tab4" role="tabpanel" aria-labelledby="tab4-tab">
            <p>Проверка с помощью OpenAI насколько резюме подходит под выбранную вакансию</p>
            <p class="text-secondary"><small>Может занять некоторое время</small></p>
            <a href="{% url 'hh:get_resume_vacancy' resume.id vacancy.id %}" class="btn btn-secondary">Проанализировать</a>
        </div>
    {% endif %}
{% endblock%}

{% block resume_tabs_cols_content %}

    <div style="border-bottom: 1px solid #bbb;  padding: 10px 0">
        <h4>{{vacancy.name}}</h4>
        <small><a href="{{vacancy.alternate_url}}">Смотреть на hh.kz</a></small><br>
        <small>Дата публикации: {{ vacancy.published_date}}</small><br>
        <span> 
            <b>
                {% if vacancy.salary_range.from != '' and vacancy.salary_range.to != '' %}
                {{ vacancy.salary_range.from }} - {{ vacancy.salary_range.to }}
                {% endif %}

                {% if vacancy.salary_range.from == '' and vacancy.salary_range.to != '' %}
                до {{ vacancy.salary_range.to }}
                {% endif %}

                {% if vacancy.salary_range.from != '' and vacancy.salary_range.to == '' %}
                от {{ vacancy.salary_range.from }}
                {% endif %}

                {% if vacancy.salary_range.currency != '' %} 
                    {{vacancy.salary_range.currency}}
                {% endif %}
            </b>
        </span>

        {% if vacancy.salary_range.mode.name != '' %}
           <span>
                {{ vacancy.salary_range.mode.name }}
           </span> 
        {% endif %}

        {% if vacancy.salary_range.gross != '' %}
           <span>
                {% if vacancy.salary_range.gross == true %}
                    до вычета налогов
                {% else %}
                    на руки
                {% endif %}
           </span> 
        {% endif %}

        {% if vacancy.experience != '' %}
           <p>
                Опыт работы: {{vacancy.experience.name}}
           </p> 
        {% endif %}

        {% if vacancy.schedule.name != '' %}
           <p>
                {{vacancy.schedule.name}}
           </p> 
        {% endif %}

        {% if vacancy.work_format%}
           <p>
            {% for format in vacancy.work_format%}
                {{format.name}} <br>
            {% endfor %}
           </p> 
        {% endif %}

        {% if vacancy.work_schedule_by_days%}
           <p>
                График: {% for schedule in vacancy.work_schedule_by_days %} {{schedule.name}} {% endfor %}
           </p> 
        {% endif %}

        {% if vacancy.working_hours %}
           <p>
            {% for hours in vacancy.working_hours %} {{hours.name}} {% endfor %}
           </p> 
        {% endif %}
        
        <div>
            <h4>Описание вакансии</h4>
            {{ vacancy.description|safe }}
        </div>
        <div>
            <h4>Ключевые навыки</h4>
            {% if vacancy.key_skills %}
                <p>
                    {% for skill in vacancy.key_skills %} {{skill.name}} {% endfor %}
                </p> 
            {% endif %}
            {% if vacancy.languages %}
                <p>
                    {% for skill in vacancy.languages %} {{skill.name}}: {{skill.level.name}}<br> {% endfor %}
                </p> 
            {% endif %}
        </div>

    </div>
    <p><a href="{% url 'hh:get_resume_vacancy' resume.id %}">Назад к списку вакансий</a></p>
{% endblock %}

hh/templates/hh/resume/get_resume_with_vacancy_list.html
{% extends "resume_detail_tabs_cols.html" %}

{% block resume_tabs_cols_content %}
    <h2>Вакансии</h2>
    {% comment %} <a href="{% url "hh:resume_upload_form" %}">Загрузить резюме</a> {% endcomment %}
    <br>
    {% for vacancy in vacancy_list %}
    <div style="border-bottom: 1px solid #bbb;  padding: 10px 0">
        <h4><a href="{% url "hh:get_resume_vacancy_detail" resume.id vacancy.id %}">{{vacancy.name}}</a></h4>
        <span> 
            <b>
                {% if vacancy.salary_from != '' and vacancy.salary_to != '' %}
                {{ vacancy.salary_from }} - {{ vacancy.salary_to }}
                {% endif %}

                {% if vacancy.salary_from == '' and vacancy.salary_to != '' %}
                до {{ vacancy.salary_to }}
                {% endif %}

                {% if vacancy.salary_from != '' and vacancy.salary_to == '' %}
                от {{ vacancy.salary_from }}
                {% endif %}

                {% if vacancy.salary_currency != '' %}
                    {{vacancy.salary_currency}}
                {% endif %}
            </b>
        </span>

        {% if vacancy.salary_mode != '' %}
           <span>
                {{ vacancy.salary_mode }}
           </span> 
        {% endif %}

        {% if vacancy.salary_gross != '' %}
           <span>
                {% if vacancy.salary_gross == true %}
                    до вычета налогов
                {% else %}
                    на руки
                {% endif %}
           </span> 
        {% endif %}

        {% if vacancy.experience != '' %}
           <p>
                Опыт работы: {{vacancy.experience}}
           </p> 
        {% endif %}

        {% if vacancy.employer_name != '' %}
           <p>
                {{vacancy.employer_name}}
           </p> 
        {% endif %}
    </div>
    {% endfor %}



{% endblock %}

hh/templates/hh/resume/resume.html
{% extends "base.html" %}

{% block title %}Мои резюме{% endblock %}

{% block content %}
    <h2>Мои резюме</h2>
    {% comment %} <a href="{% url "hh:resume_upload_form" %}">Загрузить резюме</a> {% endcomment %}
    <br>
    {% for resume in resumes %}
    <div style="border-bottom: 1px solid #bbb;  padding: 10px 0">
        <h3>{{resume.title}}</h3>
        <p>
            Статус: {{resume.status_name}}
            <br>
            Кому видно: {{resume.status_type_name}}
        </p>
        <a href="{% url "hh:get_resume" resume.id %}">Подробней</a>
    </div>
    {% endfor %}
{% endblock %}